### ISSUE TITLE
inject.js not working, bundle.umd.min.js not found

### ISSUE THREAD

**Issue by TimeBomb** [TeemuKoivisto/prosemirror-dev-toolkit#25]
I noticed https://unpkg.com/prosemirror-dev-toolkit/dist/bundle.umd.min.js doesn't exist which causes inject.js to fail to work.

**Comment by TeemuKoivisto** [comment]
Thanks @TimeBomb ! Yeah, forgot to update the build script when I migrated to pnpm. Should work now.
