### ISSUE TITLE
Skips iframes: .ProseMirror not found

### ISSUE THREAD

**Issue by kapouer** [TeemuKoivisto/prosemirror-dev-toolkit#44]
I'm loading prosemirror inside an iframe (to the same domain).
Like this:
![image](https://user-images.githubusercontent.com/131406/213721588-dbaf0338-c0a4-48a1-99af-94ae84111547.png)

The dev-toolkit chrome extension doesn't find it.
Thanks for this wonderful tool.

**Comment by TeemuKoivisto** [comment]
Hey, thanks! I'll look into it

**Comment by TeemuKoivisto** [comment]
Hey, yeah it's doable. Just kinda messy. I'll try to get the next version deployed and live soon, so you can triage

**Comment by kapouer** [comment]
Unfortunately #48 still fails to detect it.
```
document.querySelectorAll('iframe')[0].contentDocument.querySelector('.ProseMirror')
```
returns the body in the screenshot, though.

**Comment by kapouer** [comment]
I'll try to setup a demo

**Comment by kapouer** [comment]
I don't understand how to debug the code in inject.js

**Comment by TeemuKoivisto** [comment]
Inject.js? Well, it's quite complicated. If there's no error shown, the bundle is loaded but still nothing shows the injection has probably flaked. Typing into the editor might help but other than that, it's pretty hard. Can you use the unpacked extension instead?

**Comment by TeemuKoivisto** [comment]
Or well not sure how you're making the demo. Simple github.io site with iframe would probably be the best, if possible. No need to add dev-tools by hand, I can test it with the extension

**Comment by kapouer** [comment]
Yes, that's what i do. I suppose I need to add a debugger; statement somewhere in inject.js ?

**Comment by TeemuKoivisto** [comment]
You can add a debugger inside the new Promise to see whether it's actually being called. Do note thought that using inject.js to inject the dev-tools into an iframe wont work since it uses the local document object. You have to edit the querySelector logic a bit to do that.

**Comment by kapouer** [comment]
i'm seeing this
![Capture d’écran du 2023-02-21 23-33-56](https://user-images.githubusercontent.com/131406/220474459-f5a050ce-88a6-40c6-9e68-a813c2a710df.png)

`getEditorView` receives the body.ProseMirror node, however I suppose the detection is somehow assuming something that isn't there. `el.pmViewDesc` is not null, though.

**Comment by kapouer** [comment]
Hmm I see the hack :) Not easy to get prosemirror view.

**Comment by TeemuKoivisto** [comment]
Hard to say without being able to debug it myself. If the promise is never called and thus the whole function is left pending, even with user input to ProseMirror to flush the DOM, the EditorView instance just contains something unexpected. In some cases where I've had problems with it the schema was somewhat weird or there was some quirky props, like editable: false being passed.

**Comment by TeemuKoivisto** [comment]
@kapouer is this still a problem with the latest version?

**Comment by kapouer** [comment]
The last published version is 1.0.9, and that one is still failing to find body.ProseMirror in an iframe.

**Comment by kapouer** [comment]
I am trying from source 1.1.5

**Comment by kapouer** [comment]
Failing too, though it seems there is an issue when building from source.

**Comment by TeemuKoivisto** [comment]
Really? It works for TipTap iframes https://tiptap.dev/editor so there definitely is something different in the way you use them. If you can pinpoint the reason I can try out a solution but without that there isn't much I can do for now

**Comment by kapouer** [comment]
This condition still retries even when document is complete:
https://github.com/TeemuKoivisto/prosemirror-dev-toolkit/blob/cd6d0e8641835c48e67dc601b21744523bac1261/packages/extension/src/inject/utils.ts#L22

**Comment by kapouer** [comment]
Actually it works ! It detects correctly the iframe.
However it fails a bit after with this rejection:
```
setTimeout(() => {
      rej("Unable to trigger childWithSelectNode.pmViewDesc.selectNode");
    }, 1e3);
```

**Comment by TeemuKoivisto** [comment]
Oh that one. Well, it's a tricky heuristic to adjust. In most cases increasing the timeout doesn't help. Try increasing it to say 5 or 10 seconds if it helps. It has something to do with the editor being active as I recall cases where the original 1ms kept failing and why I increased it to 1s.

**Comment by kapouer** [comment]
It actually works, not right away, but several seconds after interacting with the editor.
Considering it to be nice enough :)
