### ISSUE TITLE
Disabled state not persisted

### ISSUE THREAD

**Issue by tslocke** [TeemuKoivisto/prosemirror-dev-toolkit#45]
Previous discussion: https://discuss.prosemirror.net/t/prosemirror-developer-tools-chrome-extension/5154

The chrome extension provides a switch to disable it, so you no longer see the icon, but it seems the disabled state is getting lost.

In the above conversation I was saying that this happens between Chrome sessions, but I've now noticed that the icon definitely does sometimes reappear just on a page reload.

**Comment by TeemuKoivisto** [comment]
👍 all right, I'll see when I have time to fix this and any of the other issues as well

**Comment by TeemuKoivisto** [comment]
Yeah hah, it never persisted the state in the first place 😅. Wonder how that flied past me. It'll try to get this published soon, but it'll take some time for the new extension version to go live.
