### ISSUE TITLE
Issue with injected Svelte styles

### ISSUE THREAD

**Issue by svenadlung** [TeemuKoivisto/prosemirror-dev-toolkit#46]
Not 100% grounded and completely investigated, but I have noticed that on some pages, content elements are hidden whenever this Chrome Extension is activated. 

A short investigation led to the following assumption:
The extension/DevTools uses Svelte and injects its styles at runtime. This includes a generic `hidden` class. Because it is injected in the head as a style block, the specificity is higher than the same class referenced before.

Please see the following screenshots:

Without extension:
<img width="1512" alt="Bildschirm­foto 2023-02-14 um 15 04 37" src="https://user-images.githubusercontent.com/11420688/218761099-057d4287-e6bc-493a-a64d-883fdab96ee0.png">

Activated extension:
<img width="1512" alt="Bildschirm­foto 2023-02-14 um 15 03 25" src="https://user-images.githubusercontent.com/11420688/218760602-e6f0fafb-6f46-4fdd-a909-0d2ad5c46caf.png">

This is the injection:
<img width="1158" alt="Bildschirm­foto 2023-02-14 um 15 02 24" src="https://user-images.githubusercontent.com/11420688/218760292-9e881310-97f9-411e-97be-51c835f5e978.png">

If this is correct, it will disrupt functionality on many websites, as this is also a default class of Tailwind. If possible, it should be scoped.

**Comment by TeemuKoivisto** [comment]
Hey @svenadlung ! Thanks for the bug report, yeah I've tried to fix this by using class names that ought to be unique but this only gets you so far. I'll definitely try to get the styles scoped somehow. Best way would be a web component. Second best I guess just mangling the class names, last time I checked Svelte didn't provide this out-of-the-box.
