### ISSUE TITLE
Breaking google docs/sheets

### ISSUE THREAD

**Issue by tslocke** [TeemuKoivisto/prosemirror-dev-toolkit#65]
This has just started for me - I get an error as soon as I load a google sheet or a google doc. Fixed when I disable this extension.

**Comment by TeemuKoivisto** [comment]
Hey, I was reported this error by someone else as well, turns out running the content script at `document_end` breaks Docs (for some reason). Switched to `document_start` and deployed it, try updating to v1.0.8!
