### ISSUE TITLE
multiple editors

### ISSUE THREAD

**Issue by mustafa0x** [TeemuKoivisto/prosemirror-dev-toolkit#71]
Is there a way to tell the tool which editor you'd like to inspect? Eg on this page https://tiptap.dev/experiments/multiple-editors

Thanks!

**Comment by TeemuKoivisto** [comment]
Yes with the Chrome extension. It should show a list of their contents and then you just select which one.

**Comment by mustafa0x** [comment]
Where is this list displayed? This it the dev tools, using the extension.

![image](https://github.com/TeemuKoivisto/prosemirror-dev-toolkit/assets/1473102/e0cc31c3-801d-4c0b-88a8-19d1756ec5f1)

As you can see, it shows the state of the first editor. How could I should the state of the other editors?

**Comment by TeemuKoivisto** [comment]
There's a short cut icon that comes [with the extension](https://lh3.googleusercontent.com/pQFFpccko1ksyzbpRK9op4gcx65YQyWUq2V-r5dEn1JoSBlYXFzJOY0F-4vNkW7d1DehpTqilS4qppCWXc3fSG2jaA8=w640-h400-e365-rj-sc0x00ffffff). By clicking the extensions symbol you should be able to pin it to keep it visible in the extension bar. There you can find the listed editors

**Comment by mustafa0x** [comment]
![image](https://github.com/TeemuKoivisto/prosemirror-dev-toolkit/assets/1473102/04b617b5-028f-446e-ba5c-ff7b85a2dc8d)

Found it! Awesome, thanks!
