### ISSUE TITLE
pollutes globals

### ISSUE THREAD

**Issue by mustafa0x** [TeemuKoivisto/prosemirror-dev-toolkit#74]
console was telling me windows.get was defined, which was odd. turns out in inject.js.

![image](https://github.com/TeemuKoivisto/prosemirror-dev-toolkit/assets/1473102/dce86299-44bf-43be-b0ad-f42c3b2a673f)

**Comment by TeemuKoivisto** [comment]
Uhh, that's indeed true. I published a new version, it should show up in Chrome store shortly. Thanks!

**Comment by mustafa0x** [comment]
Thanks @TeemuKoivisto!
